// <auto-generated />
using MetaForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetaForge.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MetaForgeDbContext))]
[Migration("20260715100000_AddUserDateFormatOverrides")]
public partial class AddUserDateFormatOverrides
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
