// <auto-generated />
using MetaForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetaForge.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MetaForgeDbContext))]
[Migration("20260531200000_AddReportFilterControls")]
partial class AddReportFilterControls
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
    }
}
