// <auto-generated />
using MetaForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MetaForge.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MetaForgeDbContext))]
[Migration("20260528120000_AddForgeFormActions")]
partial class AddForgeFormActions
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        // Target model is captured in MetaForgeDbContextModelSnapshot.
#pragma warning restore 612, 618
    }
}
