global using MetaForge.Application.DTOs;
global using MetaForge.Application.Interfaces;
global using MetaForge.Application.Interfaces.Repositories;
global using MetaForge.Domain.Enums;
global using MetaForge.Domain.Metadata;
global using MetaForge.Infrastructure.Persistence;
global using MetaForge.Shared.Constants;
global using MetaForge.Shared.Exceptions;
global using Microsoft.EntityFrameworkCore;
